server:
  port: 9002

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
    
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#        exclude: "env,beans"
        
spring:
  application:
    name: USER-SERVICE
#  datasource:
#    username: sa
#    url: jdbc:h2:mem:organizationdb;NON_KEYWORDS=user
#    driverClassName: org.h2.Driver
#    password: sa
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/organizationdb?useSSL=false
#    driverClassName: org.h2.Driver
    password: Goals@123
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: optional:configserver:http://localhost:9296